// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Poc.Nasa.Portal.Infrastructure.Context;

#nullable disable

namespace Poc.Nasa.Portal.Infrastructure.Migrations.NasaPortal
{
    [DbContext(typeof(NasaPortalContext))]
    [Migration("20240906180815_migration-file")]
    partial class migrationfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Poc.Nasa.Portal.Domain.Models.PictureOfTheDayAggregate.PictureOfTheDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Copyright")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("varchar(10000)");

                    b.Property<string>("HdUrl")
                        .IsRequired()
                        .HasColumnType("varchar(5000)");

                    b.Property<DateTime>("PictureDate")
                        .HasColumnType("Datetime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("varchar(5000)");

                    b.HasKey("Id");

                    b.ToTable("PictureOfTheDay", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
